In [1]:
# importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importing the data
df=pd.read_csv(r'C:\Users\Dell\Documents\people.csv')

In [3]:
df=pd.read_csv('people.csv')

In [4]:
# display top 5 records
df.head()

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.37,0.52,2,159,3,0,1,0,sales,low
4,0.41,0.50,2,153,3,0,1,0,sales,low

In [5]:
# to fetch the column names from the data
df.columns

Index(['satisfactoryLevel', 'lastEvaluation', 'numberOfProjects',
       'avgMonthlyHours', 'timeSpent.company', 'workAccident', 'left',
       'promotionInLast5years', 'dept', 'salary'],
      dtype='object')

In [6]:
# fetch you list of  the columns
list(df.columns)

['satisfactoryLevel',
 'lastEvaluation',
 'numberOfProjects',
 'avgMonthlyHours',
 'timeSpent.company',
 'workAccident',
 'left',
 'promotionInLast5years',
 'dept',
 'salary']

In [7]:
# to display the overview of a dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfactoryLevel      14999 non-null  float64
 1   lastEvaluation         14999 non-null  float64
 2   numberOfProjects       14999 non-null  int64
 3   avgMonthlyHours        14999 non-null  int64
 4   timeSpent.company      14999 non-null  int64
 5   workAccident           14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotionInLast5years  14999 non-null  int64
 8   dept                   14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [8]:
df['timeSpent.company']

0        3
1        6
2        4
3        3
4        3
        ..
14994    4
14995    2
14996    4
14997    5
14998    3
Name: timeSpent.company, Length: 14999, dtype: int64

In [10]:
df.timeSpent.company

AttributeError: 'DataFrame' object has no attribute 'timeSpent'

In [9]:
df.salary

0           low
1        medium
2        medium
3           low
4           low
          ...
14994    medium
14995       low
14996       low
14997       low
14998       low
Name: salary, Length: 14999, dtype: object

In [11]:
df.rename(columns = {'timeSpent.company':'timeSpent_company'}, inplace = True)

In [12]:
df.head()

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent_company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.37,0.52,2,159,3,0,1,0,sales,low
4,0.41,0.50,2,153,3,0,1,0,sales,low

In [13]:
# checking the shape of dataset (no of rows & no of cols)
df.shape

(14999, 10)

In [15]:
# checking for duplicate values
df.duplicated().sum()

3008

In [16]:
#to find the dupliacate values
dup=df[df.duplicated(keep='first')]
dup

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent_company,workAccident,left,promotionInLast5years,dept,salary
263,0.46,0.57,2,139,3,0,1,0,sales,low
877,0.37,0.51,2,127,3,0,1,0,sales,medium
974,0.42,0.53,2,142,3,0,1,0,sales,low
1017,0.40,0.50,2,127,3,0,1,0,IT,low
1241,0.10,0.85,6,266,4,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14985,0.95,0.84,3,270,3,1,0,1,sales,medium
14987,0.37,0.45,2,126,3,0,1,0,support,medium
14988,0.43,0.57,2,157,3,0,1,0,sales,low
14993,0.61,0.89,3,242,10,0,0,0,sales,high
14994,0.11,0.85,7,275,4,0,1,0,support,medium

In [17]:
# to remove the duplicate records
df=df.drop_duplicates(keep='first')
df

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent_company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.37,0.52,2,159,3,0,1,0,sales,low
4,0.41,0.50,2,153,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14992,0.30,0.88,5,245,4,0,0,0,hr,low
14995,0.99,0.83,4,274,2,0,0,0,sales,low
14996,0.72,0.72,4,175,4,0,0,0,technical,low
14997,0.24,0.91,5,177,5,0,0,0,sales,low
14998,0.77,0.83,6,271,3,0,0,0,support,low

In [18]:
df.shape

(11991, 10)

In [19]:
# to check the null value
df.isnull().sum()

satisfactoryLevel        0
lastEvaluation           0
numberOfProjects         0
avgMonthlyHours          0
timeSpent_company        0
workAccident             0
left                     0
promotionInLast5years    0
dept                     0
salary                   0
dtype: int64

In [20]:
from scipy.constants import pi

In [21]:
print(pi)

3.141592653589793

In [22]:
# Descriptive statistics
df.describe()

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent_company,workAccident,left,promotionInLast5years
count,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000
mean,0.629658,0.716683,3.802852,200.473522,3.364857,0.154282,0.166041,0.016929
std,0.241070,0.168343,1.163238,48.727813,1.330240,0.361234,0.372133,0.129012
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,0.480000,0.570000,3.000000,157.000000,3.000000,0.000000,0.000000,0.000000
50%,0.660000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,0.820000,0.860000,5.000000,243.000000,4.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [23]:
df.describe(include='all')

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent_company,workAccident,left,promotionInLast5years,dept,salary
count,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991,11991
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,3
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sales,low
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3239,5740
mean,0.629658,0.716683,3.802852,200.473522,3.364857,0.154282,0.166041,0.016929,NaN,NaN
std,0.241070,0.168343,1.163238,48.727813,1.330240,0.361234,0.372133,0.129012,NaN,NaN
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,0.480000,0.570000,3.000000,157.000000,3.000000,0.000000,0.000000,0.000000,NaN,NaN
50%,0.660000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000,NaN,NaN
75%,0.820000,0.860000,5.000000,243.000000,4.000000,0.000000,0.000000,0.000000,NaN,NaN
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000,NaN,NaN

Normality Test

Check whether the data is normally distributed or not in satisfactorylevel column using shapiro-wilk test

In [ ]:
# plotting histogram to visualize the distribution of data
plt.figure(figsize=(10,5))
plt.hist(df["satisfactoryLevel"])
plt.show()

In [ ]:
sns.distplot(df["satisfactoryLevel"])

In [ ]:
sns.kdeplot(x='satisfactoryLevel', data=df)

In [ ]:
# h0 - data is normally distributed
# h1 - data is not normally distributed

In [ ]:
from scipy.stats import shapiro

In [ ]:
stat,p_value=shapiro(df["satisfactoryLevel"])

In [ ]:
print(p_value)

In [ ]:
print(stat)

In [ ]:
# p value is less than 0.05 reject null hypothesis, data is not normally distributed

In [ ]:
df

In [ ]:
# salary is categorical data
df["salary"].unique()

In [ ]:
df['dept'].unique()

In [ ]:
df1=df

In [ ]:
# Converting the cat data into num, using Label Encoder 
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
df1["salary"]=l1.fit_transform(df1["salary"])  
 # fit()-> input the data
 # transform()->to apply the changes   
 # fit_transform()-> data will be inputted and necessary canges will be updated onto the object

In [ ]:
df1.head()

In [ ]:
l1=LabelEncoder()
df1["dept"]=l1.fit_transform(df1["dept"])

In [ ]:
df1['salary'].unique()

In [ ]:
df1["dept"].unique()

In [ ]:
df1.corr()

Correlation Graph

In [ ]:
plt.figure(figsize=(15,10))
sns.heatmap(df1.corr(),annot=True,cmap="BuPu")

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
# Random experiment
emp=df[(df.satisfactoryLevel>=0)&(df.satisfactoryLevel<=0.50)&(df.timeSpent_company==2)&(df.avgMonthlyHours>=130)&(df.avgMonthlyHours<=200)]

In [ ]:
emp.head()

In [ ]:
emp.shape

In [ ]:
emp["left"].value_counts()

In [ ]:
emp['left'].unique()

In [ ]:
emp['left'].nunique()

In [ ]:
emp['salary'].value_counts()

In [ ]:
emp.corr()

In [ ]:
emp["avgMonthlyHours"].mean()

T-test

In [ ]:
# t-test
# It is used to determine if there is a significant difference between the means of two groups

One sample t-test

In [ ]:
# One sample t-test - It tells us whether the means of the sample and the population are different or not

The average monthly hours of a employee having 2 years experience is 167. Is it same for employees having more than 2 years experience?

Condition - Satisfactory level of a employee is from 0-0.5 and AvgMonthlyhours is from 130-200

In [ ]:
employee=df[(df.satisfactoryLevel>=0)&(df.satisfactoryLevel<=0.50)&(df.timeSpent_company>=3)&(df.avgMonthlyHours>=130)&(df.avgMonthlyHours<=200)]

In [ ]:
employee.head()

In [ ]:
employee.shape

In [ ]:
# null hypothesis - avg monthly hours of a employee having 2 yrs exp and the employee more than that is same i.e, 167 hrs 
# alternate hypothesis - avg monthly hours of a employee having 2 yrs exp doesnot have same avg monthly hours with more than 2 yrs exp employee

In [ ]:
# selecting a random sample
sample_size= 100
sample1= employee.sample(sample_size,random_state=0)

In [ ]:
sample1

In [ ]:
employee.describe()

In [ ]:
# population mean
pos_mean=167

In [ ]:
# sample mean
print(sample1["avgMonthlyHours"].mean())

In [ ]:
from scipy.stats import ttest_1samp

In [ ]:
statistics,pvalue=ttest_1samp(sample1["avgMonthlyHours"],pos_mean)
print(statistics,pvalue)

In [ ]:
# Degrees of freedom
n=len(employee["avgMonthlyHours"])
dof=n-1
print(n,dof)

In [ ]:
#df=99

In [ ]:
alpha=0.05

In [ ]:
from scipy.stats import t

In [ ]:
cv=t.ppf([alpha/2,1-alpha/2],dof)
print(cv)

In [ ]:
# p value is less than 0.05
#reject null hypothesis,avg monthly hours is not 167 hours for employees having more than 2 yrs of exp

In [ ]:
# one sample z test for proportion

The percentage of employee leaving the company 
is 3% having experience of 2 years. Is it
 same for employees having more than 2
years experience?

In [ ]:
# Null hypothesis - percentage of employee leaving the company having the exp of 2 years is same as employee having exp more than 2 yrs
# Alternate hypothesis - percentage of employee leaving the company having the exp of 2 years is different from the employee having exp more than 2 yrs

In [ ]:
from statsmodels.stats.proportion import proportions_ztest

In [ ]:
sample_size=100

In [ ]:
sample1=employee.sample(sample_size,random_state=0)

In [ ]:
count=sample1["left"].value_counts()

In [ ]:
count

In [ ]:
nobs=len(sample1["left"])

In [ ]:
nobs

In [ ]:
p0=0.03

In [ ]:
#sample1["left"].value_counts()/nobs

In [ ]:
statistic_oneprop,pvalue_oneprop=proportions_ztest(count=count,nobs=nobs,value=p0,alternative="two-sided",prop_var=False)

In [ ]:
print(statistic_oneprop,pvalue_oneprop)

In [ ]:
# p value is less than 0.05 reject null hypothesis and accept alternate hypothesis 
# percentage of employee leaving the company having the exp of 2 years is not same as employee having exp more than 2 yrs

In [ ]:
from scipy.stats import norm
cv_norm=norm.ppf([alpha/2,1-alpha/2])
print(cv_norm)

Two sample t-test

In [ ]:
# Two sample test for means - compared the means of a two independent groups

In [ ]:
df1.head()

In [ ]:
df1["timeSpent_company"].unique()

Is the mean avg monthly hours of a employee having experience of 2-5 yrs is the same as that for employee having exp 6 - 10 yrs ?

In [ ]:
# checking the variance of both

In [ ]:
e1=df1[(df1.timeSpent_company>=2) & (df1.timeSpent_company<=5)]
e2=df1[(df1.timeSpent_company>=6) & (df1.timeSpent_company<=10)]

In [ ]:
e1.head()

In [ ]:
e1.shape

In [ ]:
e2.head()

In [ ]:
e2.shape

In [ ]:
s1=e1.sample(200,random_state=0)
s2=e2.sample(200,random_state=0)

In [ ]:
 import scipy

In [ ]:
scipy.stats.ttest_ind(s1["avgMonthlyHours"],s2["avgMonthlyHours"])

In [ ]:
# p value > 0.05 Hence accept null hypothesis
# The mean avg monthly hours of a employee having experience of 2-5 yrs is the same as that for employee having exp 6 - 10 yrs

 F-statistics

Compute the f-statistics of the previous problem statement

In [ ]:
# F-test for variance is used to test if the variances of two populations are equal.

In [ ]:
# Sample Variance 
print(s1.avgMonthlyHours.var())
print(s2.avgMonthlyHours.var())

In [ ]:
# Sample mean
print(s1.avgMonthlyHours.mean())
print(s2.avgMonthlyHours.mean())

In [ ]:
# Computing f statistic
from scipy.stats import f
F=s1.avgMonthlyHours.var()/s2.avgMonthlyHours.var()
print(F)

In [ ]:
# Degrees of freedom for sample
df1=len(s1)-1
df2=len(s2)-1

In [ ]:
import scipy.stats

In [ ]:
p_value=scipy.stats.f.cdf(F, df1, df2)
print(p_value)

In [ ]:
cv=f.ppf([alpha/2,1-alpha/2],df1, df2)
print(cv)

In [ ]:
# p value is >0.05, accept null hypothesis, equal variances